-- Cria a tabela para armazenar os cupons de desconto
CREATE TABLE public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    discount_value NUMERIC(10, 2) NOT NULL,
    points_cost INTEGER NOT NULL,
    minimum_order_value NUMERIC(10, 2) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Habilita a segurança em nível de linha
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- Política para permitir que todos vejam os cupons ativos
CREATE POLICY "Public can view active coupons"
ON public.coupons
FOR SELECT
USING (is_active = true);

-- Política para permitir que administradores gerenciem todos os cupons
CREATE POLICY "Admins can manage coupons"
ON public.coupons
FOR ALL
USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm')
WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm');

-- Insere os cupons iniciais na tabela
INSERT INTO public.coupons (name, description, discount_value, points_cost, minimum_order_value)
VALUES
    ('Cupom de R$ 5,00 de desconto', 'Válido para pedidos acima de R$ 60,00', 5.00, 60, 60.00),
    ('Cupom de R$ 10,00 de desconto', 'Válido para pedidos acima de R$ 100,00', 10.00, 100, 100.00),
    ('Cupom de R$ 25,00 de desconto', 'Válido para pedidos acima de R$ 250,00', 25.00, 250, 250.00),
    ('Cupom de R$ 50,00 de desconto', 'Válido para pedidos acima de R$ 350,00', 50.00, 500, 350.00),
    ('Cupom de R$ 75,00 de desconto', 'Válido para pedidos acima de R$ 500,00', 75.00, 750, 500.00),
    ('Cupom de R$ 100,00 de desconto', 'Válido para pedidos acima de R$ 700,00', 100.00, 1000, 700.00);