-- Tabela para armazenar os cupons que os usuários resgataram
CREATE TABLE public.user_coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    coupon_id BIGINT NOT NULL REFERENCES public.coupons(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL DEFAULT now() + interval '30 day',
    is_used BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Habilita a segurança em nível de linha
ALTER TABLE public.user_coupons ENABLE ROW LEVEL SECURITY;

-- Política: Usuários podem ver seus próprios cupons resgatados
CREATE POLICY "Users can view their own redeemed coupons"
ON public.user_coupons
FOR SELECT
USING (auth.uid() = user_id);

-- Função RPC para resgatar um cupom
CREATE OR REPLACE FUNCTION public.redeem_coupon(coupon_id_to_redeem BIGINT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  current_user_id uuid := auth.uid();
  user_points INT;
  coupon_cost INT;
BEGIN
  -- Pega os pontos do usuário e o custo do cupom
  SELECT points INTO user_points FROM public.profiles WHERE id = current_user_id;
  SELECT points_cost INTO coupon_cost FROM public.coupons WHERE id = coupon_id_to_redeem;

  -- Verifica se o cupom existe
  IF coupon_cost IS NULL THEN
    RAISE EXCEPTION 'Cupom não encontrado.';
  END IF;

  -- Verifica se o usuário tem pontos suficientes
  IF user_points < coupon_cost THEN
    RAISE EXCEPTION 'Pontos insuficientes para resgatar este cupom.';
  END IF;

  -- Subtrai os pontos do perfil do usuário
  UPDATE public.profiles
  SET points = points - coupon_cost
  WHERE id = current_user_id;

  -- Insere o cupom na tabela de cupons do usuário
  INSERT INTO public.user_coupons (user_id, coupon_id)
  VALUES (current_user_id, coupon_id_to_redeem);

  RETURN 'Cupom resgatado com sucesso!';
END;
$$;