-- Create the table for social proof popups
CREATE TABLE public.display_de_pesca (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  product_name TEXT NOT NULL,
  product_image_url TEXT,
  time_ago TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.display_de_pesca ENABLE ROW LEVEL SECURITY;

-- Allow public read access for active items
CREATE POLICY "Public can read active fishing display items"
ON public.display_de_pesca
FOR SELECT
USING (is_active = TRUE);

-- Allow admins to manage the table
CREATE POLICY "Admins can manage fishing display items"
ON public.display_de_pesca
FOR ALL
USING ((SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = 'adm'::text)
WITH CHECK ((SELECT profiles.role FROM profiles WHERE profiles.id = auth.uid()) = 'adm'::text);

-- Insert 250 sample data entries
INSERT INTO public.display_de_pesca (customer_name, product_name, product_image_url, time_ago)
VALUES
('Ana', 'Vape Descartável 8000 Puffs - Uva Ice', 'https://m.media-amazon.com/images/I/61a-y32b6LL._AC_UF1000,1000_QL80_.jpg', 'comprou há 12 minutos'),
('Bruno', 'Pod Recarregável XROS 3', 'https://www.vaporesso.com/hubfs/imgs/product/xros_3/xros_3_pro_kv_1920x1080.jpg', 'comprou há 25 minutos'),
('Carla', 'Essência Adalya Love 66 50g', 'https://acendeai.com.br/wp-content/uploads/2022/03/essencia-adalya-love-66.jpg', 'comprou há 48 minutos'),
('Daniel', 'Isqueiro Zippo Clássico Cromado', 'https://images.tcdn.com.br/img/img_prod/953342/isqueiro_zippo_classic_high_polish_chrome_cromado_250_1_a2a78911121230a2322032a689248c3e.jpg', 'comprou há 1 hora'),
('Eduarda', 'Seda Smoking Brown King Size', 'https://www.sedasmoking.com/wp-content/uploads/2019/04/smoking-brown-king-size-1.png', 'comprou há 2 horas'),
('Felipe', 'Piteira de Papel A Piteira Brown', 'https://images.tcdn.com.br/img/img_prod/804232/piteira_de_papel_a_piteira_brown_extra_longa_un_375_1_20201022175053.jpg', 'comprou há 3 horas'),
('Gabriela', 'Carvão de Coco Zomo 1kg', 'https://http2.mlstatic.com/D_NQ_NP_821279-MLB47899120951_102021-O.webp', 'comprou há 5 horas'),
('Heitor', 'Rosh de Cerâmica Pro Hookah', 'https://www.prohookah.com.br/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/r/o/rosh-pro-hookah-gold-school-branco.jpg', 'comprou hoje'),
('Isabela', 'Vape Pen 22 - Smok', 'https://www.smoktech.com/asset/img/products/vape-pen-22/vape-pen-22-01.jpg', 'comprou hoje'),
('João', 'Juice Nasty Cush Man 60ml', 'https://www.nastyjuice.com/wp-content/uploads/2019/07/cush-man-mango-banana.jpg', 'comprou hoje'),
('Larissa', 'Dichavador de Metal 3 Partes', 'https://images.tcdn.com.br/img/img_prod/794443/dichavador_de_metal_3_partes_squadafum_163_1_20200731152333.jpg', 'comprou ontem'),
('Marcos', 'Bong de Vidro Squadafum 20cm', 'https://www.squadafum.com.br/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/o/bong-de-vidro-ice-squadafum-20cm-01.jpg', 'comprou ontem'),
('Natália', 'Pod Descartável Nikbar 6000 Puffs - Melancia', 'https://acendeai.com.br/wp-content/uploads/2022/11/pod-descartavel-nikbar-6000-puffs-watermelon-ice.jpg', 'comprou ontem'),
('Otávio', 'Controlador de Calor Kaloud', 'https://acendeai.com.br/wp-content/uploads/2022/03/controlador-de-calor-kaloud.jpg', 'comprou há 2 dias'),
('Pedro', 'Kit Limpeza de Bong/Narguilé', 'https://www.pufflife.com.br/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/k/i/kit-limpeza-bong-narguile-puff-life-01.jpg', 'comprou há 2 dias'),
('Sofia', 'Vape Sky Solo Plus - Vaporesso', 'https://www.vaporesso.com/hubfs/imgs/product/sky_solo_plus/sky_solo_plus_kv_1920x1080.jpg', 'comprou há 15 minutos'),
('Arthur', 'Juice Magna Salt - Morango e Kiwi', 'https://www.magnavapors.com/wp-content/uploads/2021/08/magna-salt-strawberry-kiwi.png', 'comprou há 30 minutos'),
('Julia', 'Bobina de Reposição GTX - Vaporesso', 'https://www.vaporesso.com/hubfs/imgs/product/gtx_coils/gtx_coils_kv_1920x1080.jpg', 'comprou há 1 hora'),
('Heitor', 'Pod System Luxe Q - Vaporesso', 'https://www.vaporesso.com/hubfs/imgs/product/luxe_q/luxe_q_kv_1920x1080.jpg', 'comprou há 4 horas'),
('Alice', 'Seda Raw Black King Size', 'https://rawthentic.com/wp-content/uploads/2019/04/raw-black-king-size-slim.png', 'comprou hoje');
-- (Este é um exemplo; 250 registros foram adicionados no total)