-- 1. Create the new table to track first orders
CREATE TABLE public.primeiros_pedidos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Enable Row Level Security on the new table
ALTER TABLE public.primeiros_pedidos ENABLE ROW LEVEL SECURITY;

-- 3. Create security policies for the new table
CREATE POLICY "Users can view their own first order record" ON public.primeiros_pedidos
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Admins have full access to first orders" ON public.primeiros_pedidos
FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm');

-- 4. Create a function to handle the logic
CREATE OR REPLACE FUNCTION public.handle_first_order()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  order_count integer;
BEGIN
  -- Check if any previous order exists for this user
  SELECT count(*)
  INTO order_count
  FROM public.orders
  WHERE user_id = NEW.user_id;

  -- If this is the very first order (count will be 1), insert into the new table
  IF order_count = 1 THEN
    INSERT INTO public.primeiros_pedidos (order_id, user_id)
    VALUES (NEW.id, NEW.user_id);
  END IF;

  RETURN NEW;
END;
$$;

-- 5. Create a trigger to run the function after a new order is inserted
CREATE TRIGGER on_first_order_insert
AFTER INSERT ON public.orders
FOR EACH ROW
EXECUTE FUNCTION public.handle_first_order();