-- 1. Tabela de Níveis (Tiers)
CREATE TABLE IF NOT EXISTS public.loyalty_tiers (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    min_spend NUMERIC NOT NULL,
    max_spend NUMERIC,
    points_multiplier NUMERIC DEFAULT 1.0,
    benefits JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Garantir unicidade para evitar duplicatas
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'loyalty_tiers_name_key') THEN
        ALTER TABLE public.loyalty_tiers ADD CONSTRAINT loyalty_tiers_name_key UNIQUE (name);
    END IF;
END $$;

-- Inserir ou Atualizar os níveis
INSERT INTO public.loyalty_tiers (name, min_spend, max_spend, points_multiplier, benefits) VALUES
('Bronze', 0, 599.99, 1.0, '["1 ponto por R$1 gasto"]'),
('Prata', 600, 1199.99, 1.0, '["1 ponto por R$1 gasto", "Frete grátis 1x na semana"]'),
('Ouro', 1200, 2399.99, 1.0, '["1 ponto por R$1 gasto", "Frete grátis dias específicos", "Acesso antecipado a lançamentos"]'),
('Diamante', 2400, 3999.99, 1.5, '["1.5 pontos por R$1 gasto", "Brinde Exclusivo ANUAL", "Atendimento Prioritário", "Frete grátis 2x na semana"]'),
('Black', 4000, NULL, 2.0, '["2 pontos por R$1 gasto", "Frete Grátis SEMPRE", "Brindes recorrentes", "Pré-venda privada", "Presente de aniversário"]')
ON CONFLICT (name) DO UPDATE SET
    min_spend = EXCLUDED.min_spend,
    max_spend = EXCLUDED.max_spend,
    points_multiplier = EXCLUDED.points_multiplier,
    benefits = EXCLUDED.benefits;

-- 2. Atualizar tabela de Profiles
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS tier_id INT REFERENCES public.loyalty_tiers(id) DEFAULT 1,
ADD COLUMN IF NOT EXISTS current_tier_name TEXT DEFAULT 'Bronze',
ADD COLUMN IF NOT EXISTS spend_last_6_months NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_tier_update TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 3. Tabela de Histórico de Pontos
CREATE TABLE IF NOT EXISTS public.loyalty_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    points INT NOT NULL,
    description TEXT NOT NULL,
    operation_type TEXT CHECK (operation_type IN ('earn', 'redeem', 'adjustment', 'bonus')),
    related_order_id BIGINT REFERENCES public.orders(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Tabela de Regras de Resgate
CREATE TABLE IF NOT EXISTS public.loyalty_redemption_rules (
    id SERIAL PRIMARY KEY,
    points_cost INT NOT NULL,
    discount_value NUMERIC NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Inserir regras se não existirem (limpa duplicatas simples baseado em custo)
INSERT INTO public.loyalty_redemption_rules (points_cost, discount_value)
SELECT v.p, v.d
FROM (VALUES 
    (50, 5.00), (100, 10.00), (200, 20.00), (500, 50.00), (700, 70.00), 
    (900, 90.00), (1100, 110.00), (1300, 130.00), (1500, 150.00)
) as v(p, d)
WHERE NOT EXISTS (SELECT 1 FROM public.loyalty_redemption_rules WHERE points_cost = v.p);

-- Habilitar RLS
ALTER TABLE public.loyalty_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loyalty_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loyalty_redemption_rules ENABLE ROW LEVEL SECURITY;

-- Políticas: DROP antes de CREATE para corrigir o erro "already exists"
DROP POLICY IF EXISTS "Leitura pública de níveis" ON public.loyalty_tiers;
CREATE POLICY "Leitura pública de níveis" ON public.loyalty_tiers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Usuário vê seu histórico" ON public.loyalty_history;
CREATE POLICY "Usuário vê seu histórico" ON public.loyalty_history FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Public read redemption rules" ON public.loyalty_redemption_rules;
CREATE POLICY "Public read redemption rules" ON public.loyalty_redemption_rules FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin manage redemption rules" ON public.loyalty_redemption_rules;
CREATE POLICY "Admin manage redemption rules" ON public.loyalty_redemption_rules FOR ALL USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'adm');

-- Configurações globais
INSERT INTO public.app_settings (key, value) VALUES 
('loyalty_ticket_threshold', '500'),
('loyalty_ticket_bonus', '10'),
('loyalty_recurrence_2nd', '5'),
('loyalty_recurrence_3rd', '10'),
('loyalty_recurrence_4th', '15'),
('loyalty_referral_bonus', '50')
ON CONFLICT (key) DO NOTHING;