-- 1. Cria a tabela de logs (se não existir)
CREATE TABLE IF NOT EXISTS public.integration_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    event_type TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    payload JSONB,
    response_code INTEGER,
    details TEXT
);

-- 2. Habilita segurança (RLS)
ALTER TABLE public.integration_logs ENABLE ROW LEVEL SECURITY;

-- 3. Cria política para Admins (evita erro se já existir)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'integration_logs' AND policyname = 'Admins ver logs'
    ) THEN
        CREATE POLICY "Admins ver logs" ON public.integration_logs
        FOR SELECT TO authenticated
        USING (
            EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'adm')
        );
    END IF;
END
$$;

-- 4. Atualiza a função do Webhook para usar essa tabela
CREATE OR REPLACE FUNCTION public.trigger_new_order_webhook()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $func$
DECLARE
  headers jsonb;
  payload jsonb;
  request_id bigint;
  target_url text := 'https://n8n-ws.dkcwb.cloud/webhook/novo-pedido';
BEGIN
  -- Monta o payload
  payload := jsonb_build_object(
    'order_id', NEW.id,
    'total_price', NEW.total_price,
    'status', NEW.status,
    'payment_method', NEW.payment_method,
    'created_at', NEW.created_at,
    'user_id', NEW.user_id,
    'origin', 'database_trigger'
  );

  headers := jsonb_build_object(
    'Content-Type', 'application/json',
    'Authorization', 'Bearer ' || current_setting('supabase.service_role_key', true)
  );

  -- 1. Grava no log que estamos tentando enviar
  INSERT INTO public.integration_logs (event_type, status, payload, details)
  VALUES ('order_created', 'sending', payload, 'Disparando para ' || target_url);

  -- 2. Faz o disparo real
  SELECT
    net.http_post(
      url := target_url,
      headers := headers,
      body := payload
    ) INTO request_id;

  RETURN NEW;
EXCEPTION
  WHEN OTHERS THEN
    -- Loga o erro sem travar o pedido
    INSERT INTO public.integration_logs (event_type, status, payload, details)
    VALUES ('order_created', 'error', row_to_json(NEW), SQLERRM);
    RETURN NEW;
END;
$func$;